### ISSUE TITLE
Split bundle?

### ISSUE THREAD

**Issue by Boogie1989** [KarlDoyle/angular-es6-webpack-starter#2]
How  can i split my bundle.js to vendor.js and app.js?

**Comment by KarlDoyle** [comment]
Hi @Boogie1989 

### To rename your bundle.js file to app.js

In [webpack.config.common.babel.js](https://github.com/KarlDoyle/angular-es6-webpack-starter/blob/master/webpack.config.common.babel.js) edit this line

`filename: 'bundle.js'` to `filename: 'app.js'`

### To split your js into two files

In [webpack.config.prod.babel.js](https://github.com/KarlDoyle/angular-es6-webpack-starter/blob/master/webpack.config.prod.babel.js) make the following changes.

#### Add CommonsChunkPlugin

Change the following line
`// new webpack.optimize.CommonsChunkPlugin('common.js'),`

So it should look like this
`new webpack.optimize.CommonsChunkPlugin('vendor.js'),`

#### Add vendor modules to entry object

```
  entry : {
    bundle: path.join(__dirname,'/app/app.module.js'),
    vendor: [
      'angular', // list of angular modules
      'angular-ui-router'
    ]
  },
```


## Example webpack.config.prod.babel.js with all changes

```
import webpack from 'webpack';
import path from 'path';
import WebpackConfig from 'webpack-config';
import ngAnnotatePlugin from 'ng-annotate-webpack-plugin';

module.exports = new WebpackConfig().extend('./webpack.config.common.babel.js').merge({
  entry : {
    bundle: path.join(__dirname,'/app/app.module.js'),
    vendor: [
      'angular',
      'angular-ui-router'
    ]
  },
  plugins: [
    new webpack.optimize.CommonsChunkPlugin('vendor.js'),
    new webpack.optimize.OccurrenceOrderPlugin(true),
    new webpack.optimize.DedupePlugin(),
    new webpack.optimize.AggressiveMergingPlugin(),
    new ngAnnotatePlugin({
      add: true
    }),
    new webpack.optimize.UglifyJsPlugin({
        sourceMap: false,
        mangle: false
    })
  ]
})
```

Read more about [Webpack code splitting](https://webpack.github.io/docs/code-splitting.html#split-app-and-vendor-code)

Does this help ?

**Comment by Boogie1989** [comment]
Ok. Thanks for your fast answer!

**Comment by KarlDoyle** [comment]
@Boogie1989 - Glad to help
