### ISSUE TITLE
No HMR

### ISSUE THREAD

**Issue by Dcatfly** [KarlDoyle/angular-es6-webpack-starter#3]
I read your code, I am afraid it can‘t be achieved HMR.

**Comment by KarlDoyle** [comment]
@Dcatfly , could you explain further ?

Thanks

**Comment by Dcatfly** [comment]
Although your console to print out that sentence, but your code does not add the code to allow HMR, it can not achieve HMR function. In other words, when I modify the content of your code, the page will be the overall overload instead of HMR.

**Comment by Dcatfly** [comment]
Hello @KarlDoyle 
Although your console to print out that sentence, but your code does not add the code to allow HMR, it can not achieve HMR function. In other words, when I modify the content of your code, the page will be the overall overload instead of HMR.

**Comment by KarlDoyle** [comment]
@Dcatfly - 

Apologies for the delay, family duties called :)

The issue was with the ExtractTextPlugin, and should be resolved now. 
Thank you
