### ISSUE TITLE
Final build bundle is bigger than provided min angular.

### ISSUE THREAD

**Issue by kvindasAB** [KarlDoyle/angular-es6-webpack-starter#7]
Hello,

I saw your starter and I liked it, was trying to use it.
Although I have a fundamental doubt.

I cloned your repo and without touching anything compiled it for production.
The final size, with pretty much no code was 40X kb, which is a lot.
Then I decided to remove everything, pretty much leave module with just angular dependency, not even using ui-router or the example component.

The final size is still 310 kb, way more than angular already minified version (167kb).
Wanted to see if you have a light why is this occurring?

Thanks.

**Comment by KarlDoyle** [comment]
Hi @kvindasAB 

There was a bug in the production config file, `mangle:false` to be exact.
This has been resolved now, along with some other minor tweaks.

Thank you for raising the issue and checking out the project, let me know if you have any other feedback or requests :)
