### ISSUE TITLE
ui router with multiple views 

### ISSUE THREAD

**Issue by gjgit** [KarlDoyle/angular-es6-webpack-starter#8]
**Hello,**
I am using this starter and i like to use with it ., 

but i am having some doubts regrading UI Routers 

**How can i use different views in a this stater pack** 

for example if i have  a router called example and i have different  views in it means how to get those view files and file organization for those files with controllers 

**My example :** 

`.state('example', {
			url: '/example',
			views: {
				'': {
					templateUrl: '1.html',
					controller: '1'
				},
				'header_part': {
					templateUrl: '2.html',
					controller: '2'
				},
				'footer_part': {
					templateUrl: '3.html',
					controller: '3'
				},
				'sign_up_special_offer': {
					templateUrl: '4.html',
					controller: '4'
				}
			},
			component: 'example'
		})`

  the above code shows my state providers and routing for those files ., i implemented but can"t able to get those views  

Thanks.

**Comment by KarlDoyle** [comment]
Hi @gjgit 

Sure, glad to help. 

The framework uses [ui-router](https://github.com/angular-ui/ui-router) for routeing, 
I would recommend their [docs](https://github.com/angular-ui/ui-router) for the best resource on on learning about [nested views](https://github.com/angular-ui/ui-router/wiki/multiple-named-views).

Here is a quick example I did with the framework. 

### example.route.js

```js
function exampleRoutes($stateProvider, $urlRouterProvider) {
  $urlRouterProvider.when('', '/example');
  $urlRouterProvider.when('/', '/example');
  $stateProvider
    .state('example', {
      url: '/example',
      views: {
        '' : {
          component: 'example',
        },
        'header@example': {
          template: '<h1>Header</h1>'
        },
        'body@example': {
          template: '<h1>Body</h1>'
        },
        'footer@example': {
          template: '<h1>footer</h1>'
        },
      }
    })
}
/* @ngInject */
export default exampleRoutes;

```

### example.html

```html
<h1>{{example.title}}</h1>
<div ui-view="header"></div>
<div ui-view="body"></div>
<div ui-view="footer"></div>
```

### screenshot

![image](https://user-images.githubusercontent.com/3698173/28649511-4995432e-726d-11e7-8b07-d55c1428602b.png)

**Comment by gjgit** [comment]
hi there ., 

Thank you for your response can suppose if i have multiple controllers for multiple views means ., and if my   template and controllers are in separate folder means

`.state('sitemap', {
        url: '/sitemap.xml', // if home page means
        views: {
            '': {
                templateUrl: 'view/sitemap.xml',
                controller: 'sitemapController'
            }
        }
    })`

in this example my state having a template and it was in view/folder and sitemapController are of in other folder how tom import those things ?   

i tired with import but can"t able to get those view files which was not written like this 

`template: '<h1>Header</h1>'`  instead of  `templateUrl: 'view/sitemap.xml'`

**Comment by KarlDoyle** [comment]
Not entirely sure what your question is. 
But everything ui-router I would recommend going through their docs.

[https://ui-router.github.io/ng1/](https://ui-router.github.io/ng1/)

For imports, I generally prefer importing the contents of the file to a variable and assign the variable to the template value.

here is a good example
https://github.com/KarlDoyle/angular-es6-webpack-starter/blob/master/app/example/example.component.js
